---
- name: Install Java
  ansible.builtin.apt:
    name: default-jdk
    state: present

- name: Add Jenkins repository key
  ansible.builtin.get_url:
    url: "{{ file }}"
    dest: "{{ destination }}"
    mode: '0644'

- name: Add Jenkins repository
  ansible.builtin.copy:
    dest: "{{ dest }}"
    content: "{{ content }}"
    mode: '0644'

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Start and enable Jenkins
  service:
    name: jenkins
    state: started
    enabled: true

- name: Install UFW
  apt:
    name: ufw
    state: latest

- name: Open port for Jenkins
  ufw:
    rule: allow
    port: "8080"
...
